name: Block PR if Dependabot alerts exist

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  check-dependabot-alerts:
    name: Check Dependabot Alerts
    runs-on: ubuntu-latest

    permissions:
      security-events: read  # Required to read security alerts
      contents: read

    steps:
      - name: Check for open Dependabot alerts
        id: check_alerts
        run: |
          # Get the repo name and owner from the environment
          REPO="${{ github.repository }}"
          OWNER=$(echo "$REPO" | cut -d'/' -f1)
          REPO_NAME=$(echo "$REPO" | cut -d'/' -f2)

          # Get a list of open Dependabot alerts using GitHub's REST API
          ALERTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github+json" \
                      "https://api.github.com/repos/$REPO/dependabot/alerts?state=open")

          ALERT_COUNT=$(echo "$ALERTS" | jq '. | length')

          echo "Found $ALERT_COUNT open Dependabot alerts."

          if [ "$ALERT_COUNT" -gt 0 ]; then
            echo "❌ Blocking PR due to active Dependabot alerts."
            exit 1
          else
            echo "✅ No open Dependabot alerts found."
          fi

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
